name: Unit Tests
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
      - run: flutter build apk --split-per-abi
